version: "3.5"

services:
  frontend:
    ports:
      - 3000:3000
    build:
      context: frontend
    volumes:
      - ./frontend:/app

  backend:
    restart: always
    ports:
      - 8000:8000
    build:
      context: backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - env/backend.env

  db:
    image: postgres